spring.application.name=Backend
server.port=${PORT:8081}

# Stripe
stripe.secret-key=${STRIPE_SECRET_KEY}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:sin-configurar}
cloudinary.api-key=${CLOUDINARY_API_KEY:sin-configurar}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:sin-configurar}
